### ISSUE TITLE
Protokoll on Server - Open/Close

### ISSUE THREAD

**Issue by Marcel-Mayer-VAT** [carsharing-vaterstetten/ZK#4]
Every time someone opens or closes the car, the card-ID and the action (open or close) should be sent to the server.

For the unclear situations, an admin of the carsharer should be able to see the history of whitch ID opened or closed a specific car.

**Comment by sSANATGAR** [comment]
Nach jedem Start und Update muss ein Log geschrieben werden.

**Comment by sSANATGAR** [comment]
![Bildschirmfoto 2024-11-03 um 22 54 00](https://github.com/user-attachments/assets/6dd728be-8c67-4516-910e-ccaf0f63dff9)

ist es wie du es dir vorgestellt hast?

**Comment by Marcel-Mayer-VAT** [comment]
Mit Klaus geklärt - zunächst soll die RFID-ID mit protokolliert werden 
@sSANATGAR kannst du das noch ergänzen?
