### ISSUE TITLE
Updateing the witelist regularly

### ISSUE THREAD

**Issue by Marcel-Mayer-VAT** [carsharing-vaterstetten/ZK#8]
the device should pull the UID-whitelist every night at about 4 o'clock am.

If the download was successful, the device sends a 'OK' to the server which logs a timestamp for the device

**Comment by sSANATGAR** [comment]
Dass ein Log geschrieben werden soll, habe ich in das andere Issue aufgenommen.

**Comment by Marcel-Mayer-VAT** [comment]
Funktioniert, aber er bleibt immer wieder in dem Schritt hängen wesshalb wir jetzt auch den watchdog haben
